CREATE TABLE dictionary(
   word       VARCHAR(50) NOT NULL PRIMARY KEY
  ,thumbnail  VARCHAR(225) NOT NULL
  ,sourceLink VARCHAR(225) NOT NULL
);
INSERT INTO dictionary(word,thumbnail,sourceLink) VALUES
 ('A','https://storage.googleapis.com/resource-iconnect/Thumbnail/A.jpg','https://storage.googleapis.com/resource-iconnect/A.mp4')
,('Adik','https://storage.googleapis.com/resource-iconnect/Thumbnail/Adik.jpg','https://storage.googleapis.com/resource-iconnect/Adik.mp4')
,('Aku','https://storage.googleapis.com/resource-iconnect/Thumbnail/Aku.jpg','https://storage.googleapis.com/resource-iconnect/Aku.mp4')
,('Alpukat','https://storage.googleapis.com/resource-iconnect/Thumbnail/Alpukat.jpg','https://storage.googleapis.com/resource-iconnect/Alpukat.mp4')
,('Anak','https://storage.googleapis.com/resource-iconnect/Thumbnail/Anak.jpg','https://storage.googleapis.com/resource-iconnect/Anak.mp4')
,('Anda','https://storage.googleapis.com/resource-iconnect/Thumbnail/Anda.jpg','https://storage.googleapis.com/resource-iconnect/Anda.mp4')
,('Anggur','https://storage.googleapis.com/resource-iconnect/Thumbnail/Anggur.jpg','https://storage.googleapis.com/resource-iconnect/Anggur.mp4')
,('Angka','https://storage.googleapis.com/resource-iconnect/Thumbnail/Angka.jpg','https://storage.googleapis.com/resource-iconnect/Angka.mp4')
,('Apa','https://storage.googleapis.com/resource-iconnect/Thumbnail/Apa.jpg','https://storage.googleapis.com/resource-iconnect/Apa.mp4')
,('Apel','https://storage.googleapis.com/resource-iconnect/Thumbnail/Apel.jpg','https://storage.googleapis.com/resource-iconnect/Apel.mp4')
,('Arsitek','https://storage.googleapis.com/resource-iconnect/Thumbnail/Arsitek.jpg','https://storage.googleapis.com/resource-iconnect/Arsitek.mp4')
,('Atlet','https://storage.googleapis.com/resource-iconnect/Thumbnail/Atlet.jpg','https://storage.googleapis.com/resource-iconnect/Atlet.mp4')
,('Atletik','https://storage.googleapis.com/resource-iconnect/Thumbnail/Atletik.jpg','https://storage.googleapis.com/resource-iconnect/Atletik.mp4')
,('B','https://storage.googleapis.com/resource-iconnect/Thumbnail/B.jpg','https://storage.googleapis.com/resource-iconnect/B.mp4')
,('Badminton','https://storage.googleapis.com/resource-iconnect/Thumbnail/Badminton.jpg','https://storage.googleapis.com/resource-iconnect/Badminton.mp4')
,('Bagaimana','https://storage.googleapis.com/resource-iconnect/Thumbnail/Bagaimana.jpg','https://storage.googleapis.com/resource-iconnect/Bagaimana.mp4')
,('Baik','https://storage.googleapis.com/resource-iconnect/Thumbnail/Baik.jpg','https://storage.googleapis.com/resource-iconnect/Baik.mp4')
,('Bapak','https://storage.googleapis.com/resource-iconnect/Thumbnail/Bapak.jpg','https://storage.googleapis.com/resource-iconnect/Bapak.mp4')
,('Basket','https://storage.googleapis.com/resource-iconnect/Thumbnail/Basket.jpg','https://storage.googleapis.com/resource-iconnect/Basket.mp4')
,('Bayi','https://storage.googleapis.com/resource-iconnect/Thumbnail/Bayi.jpg','https://storage.googleapis.com/resource-iconnect/Bayi.mp4')
,('Becak','https://storage.googleapis.com/resource-iconnect/Thumbnail/Becak.jpg','https://storage.googleapis.com/resource-iconnect/Becak.mp4')
,('Belimbing','https://storage.googleapis.com/resource-iconnect/Thumbnail/Belimbing.jpg','https://storage.googleapis.com/resource-iconnect/Belimbing.mp4')
,('Besok','https://storage.googleapis.com/resource-iconnect/Thumbnail/Besok.jpg','https://storage.googleapis.com/resource-iconnect/Besok.mp4')
,('Berapa','https://storage.googleapis.com/resource-iconnect/Thumbnail/Berapa.jpg','https://storage.googleapis.com/resource-iconnect/Berapa.mp4')
,('Bodoh','https://storage.googleapis.com/resource-iconnect/Thumbnail/Bodoh.jpg','https://storage.googleapis.com/resource-iconnect/Bodoh.mp4')
,('Boros','https://storage.googleapis.com/resource-iconnect/Thumbnail/Boros.jpg','https://storage.googleapis.com/resource-iconnect/Boros.mp4')
,('Bulan','https://storage.googleapis.com/resource-iconnect/Thumbnail/Bulan.jpg','https://storage.googleapis.com/resource-iconnect/Bulan.mp4')
,('Bus','https://storage.googleapis.com/resource-iconnect/Thumbnail/Bus.jpg','https://storage.googleapis.com/resource-iconnect/Bis.mp4')
,('C','https://storage.googleapis.com/resource-iconnect/Thumbnail/C.jpg','https://storage.googleapis.com/resource-iconnect/C.mp4')
,('Cantik','https://storage.googleapis.com/resource-iconnect/Thumbnail/Cantik.jpg','https://storage.googleapis.com/resource-iconnect/Cantik.mp4')
,('Cerewet','https://storage.googleapis.com/resource-iconnect/Thumbnail/Cerewet.jpg','https://storage.googleapis.com/resource-iconnect/Cerewet.mp4')
,('D','https://storage.googleapis.com/resource-iconnect/Thumbnail/D.jpg','https://storage.googleapis.com/resource-iconnect/D.mp4')
,('Darimana','https://storage.googleapis.com/resource-iconnect/Thumbnail/Darimana.jpg','https://storage.googleapis.com/resource-iconnect/Darimana.mp4')
,('Delman','https://storage.googleapis.com/resource-iconnect/Thumbnail/Delman.jpg','https://storage.googleapis.com/resource-iconnect/Delman.mp4')
,('Desainer','https://storage.googleapis.com/resource-iconnect/Thumbnail/Desainer.jpg','https://storage.googleapis.com/resource-iconnect/Desainer.mp4')
,('Dia','https://storage.googleapis.com/resource-iconnect/Thumbnail/Dia.jpg','https://storage.googleapis.com/resource-iconnect/Dia.mp4')
,('Dimana','https://storage.googleapis.com/resource-iconnect/Thumbnail/Dimana.jpg','https://storage.googleapis.com/resource-iconnect/Dimana.mp4')
,('Dokter','https://storage.googleapis.com/resource-iconnect/Thumbnail/Dokter.jpg','https://storage.googleapis.com/resource-iconnect/Dokter.mp4')
,('Dosen','https://storage.googleapis.com/resource-iconnect/Thumbnail/Dosen.jpg','https://storage.googleapis.com/resource-iconnect/Dosen.mp4')
,('Dulu','https://storage.googleapis.com/resource-iconnect/Thumbnail/Dulu.jpg','https://storage.googleapis.com/resource-iconnect/Dulu.mp4')
,('Durian','https://storage.googleapis.com/resource-iconnect/Thumbnail/Durian.jpg','https://storage.googleapis.com/resource-iconnect/Durian.mp4')
,('E','https://storage.googleapis.com/resource-iconnect/Thumbnail/E.jpg','https://storage.googleapis.com/resource-iconnect/E.mp4')
,('Egois','https://storage.googleapis.com/resource-iconnect/Thumbnail/Egois.jpg','https://storage.googleapis.com/resource-iconnect/Egois.mp4')
,('F','https://storage.googleapis.com/resource-iconnect/Thumbnail/F.jpg','https://storage.googleapis.com/resource-iconnect/F.mp4')
,('Fotografer','https://storage.googleapis.com/resource-iconnect/Thumbnail/Fotografer.jpg','https://storage.googleapis.com/resource-iconnect/Fotografer.mp4')
,('G','https://storage.googleapis.com/resource-iconnect/Thumbnail/G.jpg','https://storage.googleapis.com/resource-iconnect/G.mp4')
,('Ganteng','https://storage.googleapis.com/resource-iconnect/Thumbnail/Ganteng.jpg','https://storage.googleapis.com/resource-iconnect/Ganteng.mp4')
,('Golf','https://storage.googleapis.com/resource-iconnect/Thumbnail/Golf.jpg','https://storage.googleapis.com/resource-iconnect/Golf.mp4')
,('Guru','https://storage.googleapis.com/resource-iconnect/Thumbnail/Guru.jpg','https://storage.googleapis.com/resource-iconnect/Guru.mp4')
,('H','https://storage.googleapis.com/resource-iconnect/Thumbnail/H.jpg','https://storage.googleapis.com/resource-iconnect/H.mp4')
,('Hari','https://storage.googleapis.com/resource-iconnect/Thumbnail/Hari.jpg','https://storage.googleapis.com/resource-iconnect/Hari.mp4')
,('I','https://storage.googleapis.com/resource-iconnect/Thumbnail/I.jpg','https://storage.googleapis.com/resource-iconnect/I.mp4')
,('Ibu','https://storage.googleapis.com/resource-iconnect/Thumbnail/Ibu.jpg','https://storage.googleapis.com/resource-iconnect/Ibu.mp4')
,('Istri','https://storage.googleapis.com/resource-iconnect/Thumbnail/Istri.jpg','https://storage.googleapis.com/resource-iconnect/Istri.mp4')
,('J','https://storage.googleapis.com/resource-iconnect/Thumbnail/J.jpg','https://storage.googleapis.com/resource-iconnect/J.mp4')
,('Jeruk','https://storage.googleapis.com/resource-iconnect/Thumbnail/Jeruk.jpg','https://storage.googleapis.com/resource-iconnect/Jeruk.mp4')
,('Jumat','https://storage.googleapis.com/resource-iconnect/Thumbnail/Jumat.jpg','https://storage.googleapis.com/resource-iconnect/Jumat.mp4')
,('K','https://storage.googleapis.com/resource-iconnect/Thumbnail/K.jpg','https://storage.googleapis.com/resource-iconnect/K.mp4')
,('Kakak','https://storage.googleapis.com/resource-iconnect/Thumbnail/Kakak.jpg','https://storage.googleapis.com/resource-iconnect/Kakak.mp4')
,('Kakek','https://storage.googleapis.com/resource-iconnect/Thumbnail/Kakek.jpg','https://storage.googleapis.com/resource-iconnect/Kakek.mp4')
,('Kalian','https://storage.googleapis.com/resource-iconnect/Thumbnail/Kalian.jpg','https://storage.googleapis.com/resource-iconnect/Kalian.mp4')
,('Kamis','https://storage.googleapis.com/resource-iconnect/Thumbnail/Kamis.jpg','https://storage.googleapis.com/resource-iconnect/Kamis.mp4')
,('Kamu','https://storage.googleapis.com/resource-iconnect/Thumbnail/Kamu.jpg','https://storage.googleapis.com/resource-iconnect/Kamu.mp4')
,('Kapal','https://storage.googleapis.com/resource-iconnect/Thumbnail/Kapal.jpg','https://storage.googleapis.com/resource-iconnect/Kapal.mp4')
,('Karate','https://storage.googleapis.com/resource-iconnect/Thumbnail/Karate.jpg','https://storage.googleapis.com/resource-iconnect/Karate.mp4')
,('Keluarga','https://storage.googleapis.com/resource-iconnect/Thumbnail/Keluarga.jpg','https://storage.googleapis.com/resource-iconnect/Keluarga.mp4')
,('Kemana','https://storage.googleapis.com/resource-iconnect/Thumbnail/Kemana.jpg','https://storage.googleapis.com/resource-iconnect/Kemana.mp4')
,('Kemarin','https://storage.googleapis.com/resource-iconnect/Thumbnail/Kemarin.jpg','https://storage.googleapis.com/resource-iconnect/Kemarin.mp4')
,('Kenapa','https://storage.googleapis.com/resource-iconnect/Thumbnail/Kenapa.jpg','https://storage.googleapis.com/resource-iconnect/Kenapa.mp4')
,('Keren','https://storage.googleapis.com/resource-iconnect/Thumbnail/Keren.jpg','https://storage.googleapis.com/resource-iconnect/Keren.mp4')
,('Kereta Api','https://storage.googleapis.com/resource-iconnect/Thumbnail/Kereta%20Api.jpg','https://storage.googleapis.com/resource-iconnect/Kereta.mp4')
,('Kita','https://storage.googleapis.com/resource-iconnect/Thumbnail/Kita.jpg','https://storage.googleapis.com/resource-iconnect/Kita.mp4')
,('Komputer','https://storage.googleapis.com/resource-iconnect/Thumbnail/Komputer.jpg','https://storage.googleapis.com/resource-iconnect/Komputer.mp4')
,('L','https://storage.googleapis.com/resource-iconnect/Thumbnail/L.jpg','https://storage.googleapis.com/resource-iconnect/L.mp4')
,('Lusa','https://storage.googleapis.com/resource-iconnect/Thumbnail/Lusa.jpg','https://storage.googleapis.com/resource-iconnect/Lusa.mp4')
,('M','https://storage.googleapis.com/resource-iconnect/Thumbnail/M.jpg','https://storage.googleapis.com/resource-iconnect/M.mp4')
,('Mangga','https://storage.googleapis.com/resource-iconnect/Thumbnail/Mangga.jpg','https://storage.googleapis.com/resource-iconnect/Mangga.mp4')
,('Manggis','https://storage.googleapis.com/resource-iconnect/Thumbnail/Manggis.jpg','https://storage.googleapis.com/resource-iconnect/Manggis.mp4')
,('Masinis','https://storage.googleapis.com/resource-iconnect/Thumbnail/Masinis.jpg','https://storage.googleapis.com/resource-iconnect/Masinis.mp4')
,('Minggu','https://storage.googleapis.com/resource-iconnect/Thumbnail/Minggu.jpg','https://storage.googleapis.com/resource-iconnect/Minggu.mp4')
,('Mobil','https://storage.googleapis.com/resource-iconnect/Thumbnail/Mobil.jpg','https://storage.googleapis.com/resource-iconnect/Mobil.mp4')
,('Motor','https://storage.googleapis.com/resource-iconnect/Thumbnail/Motor.jpg','https://storage.googleapis.com/resource-iconnect/Motor.mp4')
,('Mulai','https://storage.googleapis.com/resource-iconnect/Thumbnail/Mulai.jpg','https://storage.googleapis.com/resource-iconnect/Mulai.mp4')
,('N','https://storage.googleapis.com/resource-iconnect/Thumbnail/N.jpg','https://storage.googleapis.com/resource-iconnect/N.mp4')
,('Nahkoda','https://storage.googleapis.com/resource-iconnect/Thumbnail/Nahkoda.jpg','https://storage.googleapis.com/resource-iconnect/Nahkoda.mp4')
,('Nakal','https://storage.googleapis.com/resource-iconnect/Thumbnail/Nakal.jpg','https://storage.googleapis.com/resource-iconnect/Nakal.mp4')
,('Nelayan','https://storage.googleapis.com/resource-iconnect/Thumbnail/Nelayan.jpg','https://storage.googleapis.com/resource-iconnect/Nelayan.mp4')
,('Nenek','https://storage.googleapis.com/resource-iconnect/Thumbnail/Nelayan.jpg','https://storage.googleapis.com/resource-iconnect/Nenek.mp4')
,('O','https://storage.googleapis.com/resource-iconnect/Thumbnail/O.jpg','https://storage.googleapis.com/resource-iconnect/O.mp4')
,('Om','https://storage.googleapis.com/resource-iconnect/Thumbnail/Om.jpg','https://storage.googleapis.com/resource-iconnect/Om.mp4')
,('P','https://storage.googleapis.com/resource-iconnect/Thumbnail/P.jpg','https://storage.googleapis.com/resource-iconnect/P.mp4')
,('Pelayan','https://storage.googleapis.com/resource-iconnect/Thumbnail/Pelayan.jpg','https://storage.googleapis.com/resource-iconnect/Pelayan.mp4')
,('Pemadam Kebakaran','https://storage.googleapis.com/resource-iconnect/Thumbnail/Pemadam%20Kebakaran.jpg','https://storage.googleapis.com/resource-iconnect/Pemadam%20Kebakaran.mp4')
,('Penulis','https://storage.googleapis.com/resource-iconnect/Thumbnail/Penulis.jpg','https://storage.googleapis.com/resource-iconnect/Penulis.mp4')
,('Perawat','https://storage.googleapis.com/resource-iconnect/Thumbnail/Perawat.jpg','https://storage.googleapis.com/resource-iconnect/Perawat.mp4')
,('Pesawat','https://storage.googleapis.com/resource-iconnect/Thumbnail/Pesawat.jpg','https://storage.googleapis.com/resource-iconnect/Pesawat.mp4')
,('Pilot','https://storage.googleapis.com/resource-iconnect/Thumbnail/Pilot.jpg','https://storage.googleapis.com/resource-iconnect/Pilot.mp4')
,('Pintar','https://storage.googleapis.com/resource-iconnect/Thumbnail/Pintar.jpg','https://storage.googleapis.com/resource-iconnect/Pintar.mp4')
,('Pisang','https://storage.googleapis.com/resource-iconnect/Thumbnail/Pisang.jpg','https://storage.googleapis.com/resource-iconnect/Pisang.mp4')
,('Polisi','https://storage.googleapis.com/resource-iconnect/Thumbnail/Polisi.jpg','https://storage.googleapis.com/resource-iconnect/Polisi.mp4')
,('Presenter','https://storage.googleapis.com/resource-iconnect/Thumbnail/Presenter.jpg','https://storage.googleapis.com/resource-iconnect/Presenter.mp4')
,('Q','https://storage.googleapis.com/resource-iconnect/Thumbnail/Q.jpg','https://storage.googleapis.com/resource-iconnect/Q.mp4')
,('R','https://storage.googleapis.com/resource-iconnect/Thumbnail/R.jpg','https://storage.googleapis.com/resource-iconnect/R.mp4')
,('Rabu','https://storage.googleapis.com/resource-iconnect/Thumbnail/Rabu.jpg','https://storage.googleapis.com/resource-iconnect/Rabu.mp4')
,('Ramah','https://storage.googleapis.com/resource-iconnect/Thumbnail/Ramah.jpg','https://storage.googleapis.com/resource-iconnect/Ramah.mp4')
,('Renang','https://storage.googleapis.com/resource-iconnect/Thumbnail/Renang.jpg','https://storage.googleapis.com/resource-iconnect/Renang.mp4')
,('S','https://storage.googleapis.com/resource-iconnect/Thumbnail/S.jpg','https://storage.googleapis.com/resource-iconnect/S.mp4')
,('Sabar','https://storage.googleapis.com/resource-iconnect/Thumbnail/Sabar.jpg','https://storage.googleapis.com/resource-iconnect/Sabar.mp4')
,('Sabtu','https://storage.googleapis.com/resource-iconnect/Thumbnail/Sabtu.jpg','https://storage.googleapis.com/resource-iconnect/Sabtu.mp4')
,('Satpam','https://storage.googleapis.com/resource-iconnect/Thumbnail/Satpam.jpg','https://storage.googleapis.com/resource-iconnect/Satpam.mp4')
,('Satu Juta','https://storage.googleapis.com/resource-iconnect/Thumbnail/Satu%20Juta.jpg','https://storage.googleapis.com/resource-iconnect/Satu%20Juta.mp4')
,('Satu Miliyar','https://storage.googleapis.com/resource-iconnect/Thumbnail/Satu%20Miliyar.jpg','https://storage.googleapis.com/resource-iconnect/Satu%20Miliyar.mp4')
,('Satu Triliyun','https://storage.googleapis.com/resource-iconnect/Thumbnail/Satu%20Triliyun.jpg','https://storage.googleapis.com/resource-iconnect/Satu%20Triliun.mp4')
,('Saudara','https://storage.googleapis.com/resource-iconnect/Thumbnail/Saudara.jpg','https://storage.googleapis.com/resource-iconnect/Saudara.mp4')
,('Saya','https://storage.googleapis.com/resource-iconnect/Thumbnail/Saya.jpg','https://storage.googleapis.com/resource-iconnect/Saya.mp4')
,('Sekarang','https://storage.googleapis.com/resource-iconnect/Thumbnail/Sekarang.jpg','https://storage.googleapis.com/resource-iconnect/Sekarang.mp4')
,('Selamat Malam','https://storage.googleapis.com/resource-iconnect/Thumbnail/Selamat%20Malam.jpg','https://storage.googleapis.com/resource-iconnect/Selamat%20Malam.mp4')
,('Selamat Pagi','https://storage.googleapis.com/resource-iconnect/Thumbnail/Selamat%20Pagi.jpg','https://storage.googleapis.com/resource-iconnect/Selamat%20Pagi.mp4')
,('Selamat Siang','https://storage.googleapis.com/resource-iconnect/Thumbnail/Selamat%20Siang.jpg','https://storage.googleapis.com/resource-iconnect/Selamat%20Siang.mp4')
,('Selamat Sore','https://storage.googleapis.com/resource-iconnect/Thumbnail/Selamat%20Sore.jpg','https://storage.googleapis.com/resource-iconnect/Selamat%20Sore.mp4')
,('Selasa','https://storage.googleapis.com/resource-iconnect/Thumbnail/Selasa.jpg','https://storage.googleapis.com/resource-iconnect/Selasa.mp4')
,('Selesai','https://storage.googleapis.com/resource-iconnect/Thumbnail/Selesai.jpg','https://storage.googleapis.com/resource-iconnect/Selesai.mp4')
,('Semangka','https://storage.googleapis.com/resource-iconnect/Thumbnail/Semangka.jpg','https://storage.googleapis.com/resource-iconnect/Semangka.mp4')
,('Semua','https://storage.googleapis.com/resource-iconnect/Thumbnail/Semua.jpg','https://storage.googleapis.com/resource-iconnect/Semua.mp4')
,('Senang','https://storage.googleapis.com/resource-iconnect/Thumbnail/Senang.jpg','https://storage.googleapis.com/resource-iconnect/Senang.mp4')
,('Senin','https://storage.googleapis.com/resource-iconnect/Thumbnail/Senin.jpg','https://storage.googleapis.com/resource-iconnect/Senin.mp4')
,('Sepak Bola','https://storage.googleapis.com/resource-iconnect/Thumbnail/Sepak%20Bola.jpg','https://storage.googleapis.com/resource-iconnect/Sepakbola.mp4')
,('Sepeda','https://storage.googleapis.com/resource-iconnect/Thumbnail/Sepeda.jpg','https://storage.googleapis.com/resource-iconnect/Sepeda.mp4')
,('Sepuluh Ribu','https://storage.googleapis.com/resource-iconnect/Thumbnail/Sepuluh%20Ribu.jpg','https://storage.googleapis.com/resource-iconnect/Sepuluh%20Ribu.mp4')
,('Seratus','https://storage.googleapis.com/resource-iconnect/Thumbnail/Seratus.jpg','https://storage.googleapis.com/resource-iconnect/Seratus.mp4')
,('Seribu','https://storage.googleapis.com/resource-iconnect/Thumbnail/Seribu.jpg','https://storage.googleapis.com/resource-iconnect/Seribu.mp4')
,('Siapa','https://storage.googleapis.com/resource-iconnect/Thumbnail/Siapa.jpg','https://storage.googleapis.com/resource-iconnect/Siapa.mp4')
,('Sombong','https://storage.googleapis.com/resource-iconnect/Thumbnail/Sombong.jpg','https://storage.googleapis.com/resource-iconnect/Sombong.mp4')
,('Suami','https://storage.googleapis.com/resource-iconnect/Thumbnail/Suami.jpg','https://storage.googleapis.com/resource-iconnect/Suami.mp4')
,('Supir','https://storage.googleapis.com/resource-iconnect/Thumbnail/Supir.jpg','https://storage.googleapis.com/resource-iconnect/Supir.mp4')
,('T','https://storage.googleapis.com/resource-iconnect/Thumbnail/T.jpg','https://storage.googleapis.com/resource-iconnect/T.mp4')
,('Tahun','https://storage.googleapis.com/resource-iconnect/Thumbnail/Tahun.jpg','https://storage.googleapis.com/resource-iconnect/Tahun.mp4')
,('Tanggal','https://storage.googleapis.com/resource-iconnect/Thumbnail/Tanggal.jpg','https://storage.googleapis.com/resource-iconnect/Tanggal.mp4')
,('Tante','https://storage.googleapis.com/resource-iconnect/Thumbnail/Tante.jpg','https://storage.googleapis.com/resource-iconnect/Tante.mp4')
,('Tentara','https://storage.googleapis.com/resource-iconnect/Thumbnail/Tentara.jpg','https://storage.googleapis.com/resource-iconnect/Tentara.mp4')
,('Terima Kasih','https://storage.googleapis.com/resource-iconnect/Thumbnail/Terima%20Kasih.jpg','https://storage.googleapis.com/resource-iconnect/Terima%20kasih.mp4')
,('Tinju','https://storage.googleapis.com/resource-iconnect/Thumbnail/Tinju.jpg','https://storage.googleapis.com/resource-iconnect/Tinju.mp4')
,('Truk','https://storage.googleapis.com/resource-iconnect/Thumbnail/Truk.jpg','https://storage.googleapis.com/resource-iconnect/Truk.mp4')
,('U','https://storage.googleapis.com/resource-iconnect/Thumbnail/U.jpg','https://storage.googleapis.com/resource-iconnect/U.mp4')
,('V','https://storage.googleapis.com/resource-iconnect/Thumbnail/V.jpg','https://storage.googleapis.com/resource-iconnect/V.mp4')
,('Voli','https://storage.googleapis.com/resource-iconnect/Thumbnail/Voli.jpg','https://storage.googleapis.com/resource-iconnect/Voli.mp4')
,('W','https://storage.googleapis.com/resource-iconnect/Thumbnail/W.jpg','https://storage.googleapis.com/resource-iconnect/W.mp4')
,('X','https://storage.googleapis.com/resource-iconnect/Thumbnail/X.jpg','https://storage.googleapis.com/resource-iconnect/X.mp4')
,('Y','https://storage.googleapis.com/resource-iconnect/Thumbnail/Y.jpg','https://storage.googleapis.com/resource-iconnect/Y.mp4')
,('Z','https://storage.googleapis.com/resource-iconnect/Thumbnail/Z.jpg','https://storage.googleapis.com/resource-iconnect/Z.mp4');
